# Generated by Django 3.0.3 on 2020-02-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_post_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cellphone', models.IntegerField()),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.SmallIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Post')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='post',
            field=models.ManyToManyField(through='my_app.AuthorPost', to='my_app.Post'),
        ),
    ]
