# Generated by Django 3.0.3 on 2020-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200215_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='state',
            field=models.CharField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='state',
            field=models.CharField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, max_length=10),
        ),
    ]
