# Generated by Django 3.0.3 on 2020-02-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200215_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpost',
            name='date',
        ),
    ]
