# Generated by Django 3.0.3 on 2020-02-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_authorpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpost',
            name='date',
            field=models.DateField(default='2020-02-15'),
            preserve_default=False,
        ),
    ]
