# Generated by Django 3.0.3 on 2020-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200215_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='state',
            field=models.CharField(choices=[('Inactive', 0), ('Active', 1)], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('Inactive', 0), ('Active', 1)], default=1, max_length=10),
        ),
    ]
