# Generated by Django 3.0.3 on 2020-02-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200215_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('Inactive', 0), ('Active', 1)], default='Active', max_length=10),
        ),
    ]
